### ISSUE TITLE
[Bug] Adding item(s) to be smelted with Orthodimensional Hyperfurnace can consume less fuel

### ISSUE THREAD

**Issue by Alzarath** [Commoble/jumbo-furnace#14]
Reproduce:
Have N Orthodimensional Hyperfurnace items in the upgrade slot
Add 1 item to a smelting slot and enough fuel to smelt >1 item
Wait until the item is almost smelted
Add N items to the smelting slot(s)

Result:
All items added are smelted despite the furnace only consuming enough fuel for the 1 item (Plus whatever additional fuel it may have taken when sped up for the final few ticks).

This means I could theoretically add 1 item and, with good timing and enough Orthodimensional Hyperfurnace upgrades, smelt a whole stack at the overall cost of 1 or 2 units of fuel.

**Comment by Commoble** [comment]
Fixed in 1.21
