### ISSUE TITLE
[Suggestion] Jumno furnace - 18.2 please

### ISSUE THREAD

**Issue by DragonGirl7567** [Commoble/jumbo-furnace#17]
add an 18.2 version please, or at least tell how to use for 18.2

So sorry to bother you if you get too many asks about this, or if you are working on it at the moment, so sorry

**Comment by Commoble** [comment]
nope, I don't backport mods to older versions

the mod is open-source though so anybody else who wants to do it is welcome to

**Comment by DragonGirl7567** [comment]
ok, sorry
