### ISSUE TITLE
[BUG 1192] tag count / results

### ISSUE THREAD

**Issue by 2929762171** [Commoble/jumbo-furnace#24]
ingredients:tag/count didn't work
![image](https://github.com/Commoble/jumbo-furnace/assets/98941945/b29a0821-3492-4f4d-ae84-98093319b3b6)
![image](https://github.com/Commoble/jumbo-furnace/assets/98941945/1e717b63-2f51-441f-9635-a5ee026abff0)

"results" can't be use
![image](https://github.com/Commoble/jumbo-furnace/assets/98941945/ef5228b4-e33e-4f24-9703-2f307d98a725)
```log
Error parsing recipe jumbofurnace:test[jumbofurnace:jumbo_smelting]: {"type":"jumbofurnace:jumbo_smelting","ingredients":[{"type":"forge:nbt","item":"minecraft:diamond_ore","count":1},{"tag":"forge:storage_blocks/coal","count":3}],"results":[{"id":"minecraft:deepslate_diamond_ore"}],"experience":0.1}: com.google.gson.JsonSyntaxException: Missing result, expected to find a JsonObject
```

**Comment by Commoble** [comment]
You're using the 1.21 format. For 1.19.2 you need to use the jumbofurnace:tag_stack ingredient and the 1.19 recipe format

![tag_stack](https://github.com/Commoble/jumbo-furnace/assets/12983805/63039293-5142-42fc-9e77-4ece4e0e0fe0)
