### ISSUE TITLE
[bug 1192] fuel cost

### ISSUE THREAD

**Issue by 2929762171** [Commoble/jumbo-furnace#25]
jumbofurnace-1.19.2-3.0.0.0

normally, 64 iron ore cost 8 coal
![image](https://github.com/Commoble/jumbo-furnace/assets/98941945/706a8779-d98f-4524-9d9c-137a377e65e2)
![image](https://github.com/Commoble/jumbo-furnace/assets/98941945/199af608-d869-4a5a-8748-ef8e6974438f)

but when something is about to be smelted, and put 64 iron ore as input
![image](https://github.com/Commoble/jumbo-furnace/assets/98941945/264cd39a-4f3b-4bee-8f64-0b75aa3bf6e3)
it will just cost less then 8 coal
![image](https://github.com/Commoble/jumbo-furnace/assets/98941945/5ab100ed-451e-4c82-8aea-565157bed336)

**Comment by Commoble** [comment]
I fixed this in 1.21
