### ISSUE TITLE
JEI Recipes are glitched

### ISSUE THREAD

**Issue by PinkLasagna03** [Commoble/jumbo-furnace#27]
Forge 1.20.1, v47.3.6 
Jumbo Furnace v4.0.0.5
JEI v15.20.0.105

![2024-10-28_23 16 03](https://github.com/user-attachments/assets/cd3c35e2-5b80-4c7a-9fd7-1eb691c4864e)

**Comment by Commoble** [comment]
I'm no longer maintaining 1.20.1, you can fix this by downgrading JEI
