### ISSUE TITLE
Tickrate problem

### ISSUE THREAD

**Issue by PatriotCZ** [Commoble/jumbo-furnace#30]
Minecraft version 1.20.1.
Forge 47.3.0
Jumbo 4.0.0.5

When playing on heavily modded save/server (200+ mods)
While smelting anything in the furnace, tickrate of the server increases slowly forever until it gets so high that the server starts lagging a lot. As long as the furnace is fired up its constantly getting higher. When the furnace stops burning, tickrate drops again on its natural low levels.

**Comment by Commoble** [comment]
Can you reproduce it on 1.21.1? I rewrote how the furnace works so whatever causes this might not exist anymore

**Comment by PatriotCZ** [comment]
I can confirm that on 1.21.1 neoforge, the problem is not appearing. Any chance to fix this for the 1.20.1?
