### ISSUE TITLE
question/suggestion

### ISSUE THREAD

**Issue by Rithenar** [Commoble/jumbo-furnace#5]
Playing on 1.16.3

Have you thought about allowing or adding some kind of external heat source instead of regular solid fuels? Is this completely out of the question with the vision of the mod or something to consider?  I tried using the IE heater which works with regular furnaces.

**Comment by Commoble** [comment]
I might eventually make some kind of electric jumbo furnace but I don't have any plans at the moment.
Things that make regular furnaces do things like that work because they're specifically looking for regular furnaces.
