### ISSUE TITLE
Furnace input items disappearing, significant loss in items smelted.

### ISSUE THREAD

**Issue by Andr0oS** [Commoble/jumbo-furnace#6]
Running version: jumbofurnace-1.16.3-2.1.0.0.jar
in pack:  All the Mods 6- 1.1.5 (for 1.16.3)
Forge version: 34.1.23
Singleplayer instance
Terracotta recipe produces only half as much as regular furnace, items disappear in input slots, actual outputs are not equal to the expected outputs.

**Comment by Commoble** [comment]
I downloaded All The Mods 6 1.1.5 for 1.16.3, made a new singleplayer world, confirmed that the Forge version and Jumbo Furnace version were correct, and smelted some white terracotta. White Terracotta smelted normally. Added a full stack of hyperfurnace upgrades, smelted a stack of 64 white terracotta into 64 white glazed terracotta as normal. Attempted with orange terracotta, same results. Attempted with regular terracotta, could not smelt -- then double-checked recipes and determined that regular terracotta does not smelt into anything in this modpack (confirmed via standard furnace as well). Placed 9 different colors of terracotta into furnace (with 3 items per stack) into furnace -- smelted into the correct amounts of glazed terracotta both without and with hyperfurnace upgrades. Have not been able to reproduce this bug report.

**Comment by Andr0oS** [comment]
I should be clear, it was clay smelting into Terracotta.
Strange, I could repeat it yesterday with no issue, but now I'm not able to - upgrades or no upgrades. I honestly don't know what's changed, nothing's been updated. The issue with stacks being messed up is gone too. I'll see if I can replicate it again in the next few days.

**Comment by 4Magma** [comment]
i had also losses and it seems it occur when i 
shift-(ctrl-)click items in while furnace already working.
I added few new items but they had dissappeared.

**Comment by Commoble** [comment]
Fixed in 2.2.0.0 / https://github.com/Commoble/jumbo-furnace/commit/43780864a4a06187461d7a0e732c7c8a1a1da209
