### ISSUE TITLE
[Bug] furnace drops item if output full instead to stop

### ISSUE THREAD

**Issue by 4Magma** [Commoble/jumbo-furnace#7]
Hi
 
- jumbofurnace-1.16.3-2.1.0.0.jar 
- forge-1.16.3-34.1.25 (but was already with earlier version)

issue:
- jumbofurnace drops items if output is full
- testet with and without upgrades

expected:
- furnace stops if not enough room for output

**Comment by toktoktheeo** [comment]
Hi,

I have the same bug.

Minecraft 1.16.4
Forge 35.1.36
Jumbo Furnace 2.2.0.1

Have a nice day,

**Comment by Commoble** [comment]
Fixed in 1.20.1-4.0.0.3
